### ISSUE TITLE
Adding a secret to a module incorrectly causes panic

### ISSUE THREAD

**Issue by wesbillman** [block/ftl#3547]
I was incrementally adding a secret value to the `echo` module while `ftl dev` was running. When I added this line to `echo.go` and hit save I got a panic

```
type MySecret = ftl.Secret[string]
```

```sh
> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x102a0779c]

goroutine 223 [running]:
github.com/TBD54566975/ftl/internal/schema.ModuleFromProto(0x140006a5260?)
	/Users/wesbillman/dev/ftl/internal/schema/module.go:273 +0x1c
github.com/TBD54566975/ftl/internal/schema/schemaeventsource.New.func1({0x140004863c0?, 0x1044611e0?}, 0x140065c4de0)
	/Users/wesbillman/dev/ftl/internal/schema/schemaeventsource/schemaeventsource.go:143 +0x4c
github.com/TBD54566975/ftl/internal/rpc.RetryStreamingServerStream[...]({0x10444b1b8, 0x14000b99470}, {0x1038b9f7b, 0xb}, {0x0, 0x0, 0x0, 0x0, 0x0}, 0x1400034c630, ...)
	/Users/wesbillman/dev/ftl/internal/rpc/rpc.go:287 +0x498
created by github.com/TBD54566975/ftl/internal/schema/schemaeventsource.New in goroutine 222
	/Users/wesbillman/dev/ftl/internal/schema/schemaeventsource/schemaeventsource.go:142 +0x49c
```

**Comment by wesbillman** [comment]
I think this issue is resolved. I tried it again today and it worked well an no panic occurred.
